#!/bin/bash

INITIAL_DIR="$(pwd)"
CONFIGS_DIR="$INITIAL_DIR/src"

if [[ -d "$CONFIGS_DIR" ]]; then
    cd "$CONFIGS_DIR"
    find . -maxdepth 1 -type f -exec cp -r '{}' ~/ ';'    
else
    echo "Configs dir not found"
fi
